# Import dependencies and determine working directory

In [1]:
# Import libraries
import numpy as np
from os import path
from sklearn.externals import joblib
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

# Load training data

In [2]:
# Load data from pickled file 
filename_in__images_train = path.join('..', '04_processed_data','images_train.pkl')
filename_in__emotions_train = path.join('..', '04_processed_data','emotions_train.pkl')

X_train = joblib.load(filename_in__images_train)
y_train = joblib.load(filename_in__emotions_train)

In [3]:
filename_in__images_test = path.join('..', '04_processed_data','images_test.pkl')
filename_in__emotions_test = path.join('..', '04_processed_data','emotions_test.pkl')

X_test = joblib.load(filename_in__images_test)
y_test = joblib.load(filename_in__emotions_test)

# Build a KNN model

In [6]:
# train and evaluate a k-NN classifer on the raw pixel intensities
print("Model raw pixels...")
model = KNeighborsClassifier(n_neighbors=8)
model.fit(X_train, y_train)

# Predict training values
train_prediction = model.predict(X_train)
# Compute training accuracy
accuracy = metrics.accuracy_score(y_train, train_prediction)
print("Raw pixel training accuracy: {:.2f}%".format(accuracy * 100))
# Calculate and print the confusion matrix
cm = metrics.confusion_matrix(y_train, train_prediction, labels=[0,1,2,3,4,5,6,7])
print('For the confusion matrix, rows correspond to actual ratings and the columns correspond to predicted ratings.')
print(cm)

Model raw pixels...
Raw pixel training accuracy: 83.59%
For the confusion matrix, rows correspond to actual ratings and the columns correspond to predicted ratings.
[[1025   37   21   20   11   31   20   11]
 [  90  631    1    4    4    4    5    0]
 [  15    1  133    0    0    0    2    0]
 [ 122   24    2  406    4    6    3    1]
 [  49    2    0    0  358    3    1    0]
 [ 120    4    1    5    0  818    0    1]
 [  62   17    0    5    2    0  292    0]
 [ 123    5    0    5    4   10   11  765]]


# Evaluate KNN model

In [7]:
# Predict test values
test_prediction = model.predict(X_test)
# Compute test accuracy
accuracy = metrics.accuracy_score(y_test, test_prediction)
print("Raw pixel training accuracy: {:.2f}%".format(accuracy * 100))
# Calculate and print the confusion matrix
cm = metrics.confusion_matrix(y_test, test_prediction, labels=[0,1,2,3,4,5,6,7])
print('For the confusion matrix, rows correspond to actual ratings and the columns correspond to predicted ratings.')
print(cm)

Raw pixel training accuracy: 22.97%
For the confusion matrix, rows correspond to actual ratings and the columns correspond to predicted ratings.
[[111   8   4   0   2   1   4   2]
 [ 61   5   4   5   7   4  17   0]
 [  5   3   0   0   2   0   0   0]
 [ 35   2   3   1   2  21   0   0]
 [ 23   0   0   0   0   0   0  10]
 [ 76   2   0  17   0   3   5   3]
 [ 33  10   7   2   0   0   0   5]
 [ 45   2   0  10   2   2   0  13]]
